version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: dwarner-verus-electrum_app_1
      APP_PORT: 3000

  app:
    image: ghcr.io/dwarner5522/umbrel-verus-electrum:v1.8.6-1@sha256:0421a005a122b64a457701c42a56d8cf20b482ff593e2027c806c6602259c6ea
    user: "1000:1000"
    init: true
    restart: on-failure
    # ElectrumX flushes its index to disk on shutdown
    stop_grace_period: 2m
    # this port is exposed for wallets connecting to the Electrum server
    ports:
      - "${APP_VERUS_ELECTRUM_PORT}:${APP_VERUS_ELECTRUM_PORT}"
    volumes:
      - ${APP_DATA_DIR}/data/electrumx:/data
    environment:
      # VERUS NODE (from the Verus Node app)
      DAEMON_HOST: "dwarner-verus_app_1"
      DAEMON_RPC_PORT: "${APP_VERUS_RPC_PORT}"
      DAEMON_RPC_USER: "${APP_VERUS_RPC_USER}"
      DAEMON_RPC_PASS: "${APP_VERUS_RPC_PASS}"

      # ELECTRUM SERVER
      ELECTRUM_PORT: "${APP_VERUS_ELECTRUM_PORT}"

      # CONNECTION DETAILS (shown to user in the app)
      DEVICE_DOMAIN_NAME: "${DEVICE_DOMAIN_NAME}"
